config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'

  get 'admin' => 'admin#index'

  controller :sessions do
    get    'login'  => :new
    post   'login'  => :create
    delete 'logout' => :destroy
  end

  resources :products do
    get :cost, on: :collection
  end

  resources :dishes do
    get :sales, on: :collection
  end
  
  resources :users
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, uniqueness: true, presence: { message: 'Nome não pode ficar em branco' }

  after_destroy :ensure_an_admin_remains

  class Error < StandardError
  end
  
  private

  def ensure_an_admin_remains
    if User.count.zero?
      raise Error.new 'Não é possível deletar o último usuário!'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  rescue_from 'User::Error' do |exception|
    redirect_to users_url, notice: exception.message
  end

  def index
    @users = User.order(:name)
  end

  def show
    fresh_when @user
  end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: "Usuário #{@user.name} criado com sucesso."
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "Usuário #{@user.name} atualizado com sucesso."
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'Usuário deletado com sucesso.'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |f| %>
  <%= error_messages_for(f.object) %>

  <div class="form-group">
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name, class: 'input_session_name form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password, 'Senha' %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, 'Confirme sua senha' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit action_text, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editar usuário</h1>

<%= render partial: 'form', locals: { user: @user, action_text: 'Atualizar Usuário' } %>

<%= link_to 'Mostrar', @user %> |
<%= link_to 'Voltar', users_path %>

app/views/users/index.html.erb
<%= flash_message %>

<h1>Usuários</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th scope="col">Nome</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Mostrar', user %></td>
        <td><%= link_to 'Editar', edit_user_path(user) %></td>
        <td><%= link_to 'Deletar', user, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>Novo Usuário</h1>

<%= render partial: 'form', locals: { user: @user, action_text: 'Novo Usuário' } %>

<%= link_to 'Voltar', users_path %>

app/views/users/show.html.erb
<%= flash_message %>

<div class="card">
  <div class="card-body">
    <dl class="row">
      <dt class="col-sm-2">Nome</dt>
      <dd class="col-sm-9"><%= @user.name %></dd>
    </dl>
  </div>
</div>

<%= link_to 'Editar', edit_user_path(@user) %> |
<%= link_to 'Voltar', users_path %>