config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'

  get 'admin' => 'admin#index'

  controller :sessions do
    get    'login'  => :new
    post   'login'  => :create
    delete 'logout' => :destroy
  end

  resources :products do
    get :cost, on: :collection
  end

  resources :dishes do
    get :sales, on: :collection
  end
  
  resources :users
end

app/views/shared/_header.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
  <h5 class="my-0 mr-md-auto font-weight-normal">Bistro Calixto</h5>
  <nav class="my-2 my-md-0 mr-md-3">
    <div class="p-2 text-dark"><%= current_user.name %></div>
  </nav>
  <%= link_to 'Sair', logout_path, method: :delete, class: 'btn btn-outline-primary' %>
</div>

app/views/shared/_side_menu.html.erb
<ul class="nav nav-pills flex-column mb-3">
  <!--
  <li class="nav-item">
    <%= link_to 'Dashboard', admin_path, class: "nav-link #{'active' if params[:controller] == 'admin' }" %>
  </li>
  -->
  <li class="nav-item">
    <%= link_to 'Despesas', cost_products_path, class: "nav-link #{'active' if params[:controller] == 'products' && params[:action] == 'cost' }" %>
  </li>
  <li class="nav-item">
    <%= link_to 'Vendas', sales_dishes_path, class: "nav-link #{'active' if params[:controller] == 'dishes' && params[:action] == 'sales' }" %>
  </li>
</ul>

<hr>

<ul class="nav nav-pills flex-column mb-3">
  <li class="nav-item">
    <%= link_to 'Estoque', products_path, class: "nav-link #{'active' if params[:controller] == 'products' && params[:action] == 'index' }" %>
  </li>
  <li class="nav-item">
    <%= link_to 'Novo Produto', new_product_path, class: "nav-link #{'active' if current_page?(new_product_path) }" %>
  </li>
</ul>

<hr>

<ul class="nav nav-pills flex-column bm-3">
  <li class="nav-item">
    <%= link_to 'Pratos', dishes_path, class: "nav-link #{'active' if params[:controller] == 'dishes' && params[:action] == 'index' }" %>
  </li>
  <li class="nav-item">
    <%= link_to 'Novo Prato', new_dish_path, class: "nav-link #{'active' if current_page?(new_dish_path) }" %>
  </li>
</ul>

<hr>

<ul class="nav nav-pills flex-column bm-3">
  <li class="nav-item">
    <%= link_to 'Usuários', users_path, class: "nav-link #{'active' if params[:controller] == 'users' && params[:action] == 'index' }" %>
  </li>
  <li class="nav-item">
    <%= link_to 'Novo Usuário', new_user_path, class: "nav-link #{'active' if current_page?(new_user_path) }" %>
  </li>
</ul>