config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'

  get 'admin' => 'admin#index'

  controller :sessions do
    get    'login'  => :new
    post   'login'  => :create
    delete 'logout' => :destroy
  end

  resources :products do
    get :cost, on: :collection
  end

  resources :dishes do
    get :sales, on: :collection
  end
  
  resources :users
end

app/models/dish.rb
class Dish < ApplicationRecord
  paginates_per 15
  
  validates :name,    presence: { message: 'Nome não pode ficar em branco' }
  validates :price,   presence: { message: 'Preço deve ser maior que zero' },
                                  numericality: { greater_than_or_equal_to: 0 }
                 

  has_many :item_dishes
  has_many :products, through: :item_dishes, dependent: :destroy

  accepts_nested_attributes_for :item_dishes

end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: [:show, :edit, :update, :destroy]

  rescue_from 'ItemDish::Error' do |exception|
    redirect_to new_dish_path, notice: exception.message
  end

  def index
    @dishes = Dish.order('id DESC').page(params[:page])
  end

  def show
    fresh_when @dish
  end

  def new
    @dish = Dish.new
    @products = Product.available_amount
    if @products.empty?
      redirect_to new_product_path, notice: 'Primeiramente cadastre um produto.'
    end
  end

  def edit
    @products = Product.available_amount
  end

  def create
    @dish = Dish.new(dish_params)

    create_item_dishes
    if @dish.save
      redirect_to @dish, notice: 'Prato criado com sucesso.'
    else
      @products = Product.available_amount
      render :new
    end
  end

  def update
    create_item_dishes
    if @dish.update(dish_params)
      redirect_to @dish, notice: 'Prato atualizado com sucesso.'
    else
      render :edit
    end
  end

  def destroy
    @dish.destroy
    redirect_to dishes_url, notice: 'Prato deletado com sucesso.'
  end

  def sales
    if params[:search]
      search_date   = params[:search][:month]
      search_date ||= params[:search][:week]

      if search_date.present?
        start_date = end_date = Date.parse(search_date.gsub('-', '/'))
      end
    end

    start_date = end_date ||= Time.now

    week_relation  = Dish.where(created_at: start_date.beginning_of_week..end_date.end_of_week).select('price, count(id)').group('price, id')
    month_relation = Dish.where(created_at: start_date.beginning_of_month..end_date.end_of_month).select('price, count(id)').group('price, id')

    @week_costs = week_relation.sum(&:price)
    @week_size = week_relation.length

    @month_costs = month_relation.sum(&:price)
    @month_size = month_relation.length
  end

  private

  def set_dish
    @dish = Dish.find(params[:id])
  end

  def dish_params
    params.require(:dish).permit(:name, :description, :price)
  end

  def create_item_dishes
    return unless params[:item_dishes].present?

    amounts =  params[:item_dishes][:amount]

    amounts.each_with_index do |amount, index|
      product_id = params[:item_dishes][:product_id][index]
      measure = params[:item_dishes][:measure][index]
      @dish.item_dishes.build(product_id: product_id, amount: amount, measure: measure)
    end
  end
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/_form.html.erb
<%= form_with(model: dish, local: true) do |f| %>
  <%= error_messages_for(f.object) %>

  <div class="form-group">
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description, 'Descrição' %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :price, 'Preço' %>
    <%= f.number_field :price, min: 1, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= label_tag 'dishes_name', 'Pesquisar Produtos' %>
    <%= text_field_tag 'dishes_name', nil, class: 'form-control' %>
  </div>

  <div class="form-group row" id="amount_dishes_selected">
  </div>

  <div class="actions">
    <%= f.submit action_text, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/dishes/edit.html.erb
<h1>Editar Prato</h1>

<%= render partial: 'form', locals: { dish: @dish, action_text: 'Atualizar Prato' } %>

<%= link_to 'Mostrar', @dish %> |
<%= link_to 'Voltar', dishes_path %>

app/views/dishes/index.html.erb
<%= flash_message %>

<h1>Pratos</h1>

<%= paginate @dishes %>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th scope="col">Nome</th>
      <th scope="col">Descrição</th>
      <th scope="col">Preço</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dishes.each do |dish| %>
      <tr>
        <td><%= dish.name %></td>
        <td><%= dish.description %></td>
        <td>R$ <%= dish.price %></td>
        <td><%= link_to 'Mostrar', dish %></td>
        <!-- 
          <td><%= link_to 'Editar', edit_dish_path(dish) %></td> 
        -->
        <td><%= link_to 'Deletar', dish, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @dishes %>

app/views/dishes/new.html.erb
<h1>Novo Prato</h1>

<%= render partial: 'form', locals: { dish: @dish, action_text: 'Novo Prato' } %>

<%= link_to 'Voltar', dishes_path %>

app/views/dishes/sales.html.erb
<div class="card-deck mb-3 text-center">
  <div class="card mb-4 box-shadow">
    <div class="card-header">
      <h4 class="my-0 font-weight-normal">Por mês</h4>
      <%= form_tag sales_dishes_path, method: "get" do %>
        <%= month_field(:search, :month) %>
        <%= submit_tag 'Filtrar', class: 'btn btn-primary' %>
      <% end %>
    </div>
    <div class="card-body">
      <h1 class="card-title pricing-card-title">R$ <%= @month_costs %> <small class="text-muted">/ mês</small></h1>
      <ul class="list-unstyled mt-3 mb-4">
        <li><%= @month_size %> Pratos foram vendidos</li>
      </ul>
    </div>
  </div>
  
  <div class="card mb-4 box-shadow">
    <div class="card-header">
      <h4 class="my-0 font-weight-normal">Por semana</h4>
      <%= form_tag sales_dishes_path, method: "get" do %>
        <%= week_field(:search, :month) %>
        <%= submit_tag 'Filtrar', class: 'btn btn-primary' %>
      <% end %>
    </div>
    <div class="card-body">
      <h1 class="card-title pricing-card-title">R$ <%= @week_costs %> <small class="text-muted">/ semana</small></h1>
      <ul class="list-unstyled mt-3 mb-4">
        <li><%= @week_size %> Pratos foram vendidos</li>
      </ul>
    </div>
  </div>
</div>

app/views/dishes/show.html.erb
<%= flash_message %>

<div class="card">
  <div class="card-body">
    <dl class="row">
      <dt class="col-sm-2">Nome</dt>
      <dd class="col-sm-9"><%= @dish.name %></dd>

      <dt class="col-sm-2">Descrição</dt>
      <dd class="col-sm-9"><%= @dish.description %></dd>

      <dt class="col-sm-2">Preço</dt>
      <dd class="col-sm-9"><%= @dish.price %></dd>

      <dt class="col-sm-2">Items</dt>
      <dd class="col-sm-9"><%= @dish.item_dishes.map(&:name_with_amount_and_measure).join(', ') %></dd>
    </dl>
  </div>
</div>

<%= link_to 'Editar', edit_dish_path(@dish) %> |
<%= link_to 'Voltar', dishes_path %>