config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'

  get 'admin' => 'admin#index'

  controller :sessions do
    get    'login'  => :new
    post   'login'  => :create
    delete 'logout' => :destroy
  end

  resources :products do
    get :cost, on: :collection
  end

  resources :dishes do
    get :sales, on: :collection
  end
  
  resources :users
end

app/models/product.rb
class Product < ApplicationRecord
  paginates_per 15

  MEASURES = [ :kilogramas, :gramas, :litros, :mililitros ].freeze

  validates :name,    presence: { message: 'Nome não pode ficar em branco' }
  validates :measure, presence: { message: 'Medida não pode ficar em branco' }
  validates :brand,   presence: { message: 'Marca não pode ficar em branco' }
  validates :amount,  presence: { message: 'Quantidade não pode ficar em branco' },
                                  numericality: { greater_than_or_equal_to: 0 }

  validate :expiration_date_cannot_be_in_the_past

  has_many :item_dishes
  has_many :dishes, through: :item_dishes, dependent: :destroy

  scope :available_amount, -> { where('amount > 0') }

  def name_with_amount_and_measure
    "#{name} - #{amount} - (#{measure})"
  end

  def self.search(name)
    where('lower(name) like ?', "%#{name}%")
  end

  private

  def expiration_date_cannot_be_in_the_past
    if expiration_date.present? && expiration_date < Date.today
      errors.add(:expiration_date, "Data de expiração não pode estar no passado.")
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    if params[:q]
      @products = Product.search(params[:q])
      render json: @products, status: :ok
    end
    @products = Product.order('id DESC').page(params[:page])
  end

  def show
    fresh_when @product
  end

  def new
    @product = Product.new
  end

  def edit; end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product, notice: 'Produto cadastrado sucesso'
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Produto atualizado com sucesso'
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Produto excluído com sucesso'
  end

  def cost
    if params[:search]
      search_date   = params[:search][:month]
      search_date ||= params[:search][:week]

      if search_date.present?
        start_date = end_date = Date.parse(search_date.gsub('-', '/'))
      end
    end

    start_date = end_date ||= Time.now

    week_relation  = Product.where(created_at: start_date.beginning_of_week..end_date.end_of_week).select('price, count(id)').group('price, id')
    month_relation = Product.where(created_at: start_date.beginning_of_month..end_date.end_of_month).select('price, count(id)').group('price, id')

    @week_costs = week_relation.sum(&:price)
    @week_size = week_relation.length

    @month_costs = month_relation.sum(&:price)
    @month_size = month_relation.length
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :purchase_date, :expiration_date, :brand, :amount, :price, :measure)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |f| %>
  <%= error_messages_for(f.object) %>

  <div class="form-group">
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group col-md-5 pl-0">
    <%= f.label :purchase_date, 'Data de compra' %>
    <div>
      <%= f.date_select :purchase_date, {}, class: 'form-control date-select' %>
    </div>
  </div>

  <div class="form-group col-md-5 pl-0">
    <%= f.label :expiration_date, 'Data de vencimento' %>
    <div>
      <%= f.date_select :expiration_date, {}, class: 'form-control date-select' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :brand, 'Marca' %>
    <%= f.text_field :brand, class: 'form-control' %>
  </div>

  <div class="row">
    <div class="col">
      <div class="form-group">
        <%= f.label :amount, 'Quantidade' %>
        <%= f.number_field :amount, min: 1, class: 'form-control' %>
      </div>
    </div>
    <div class="col">
      <div class="form-group">
        <%= f.label :measure, 'Medida' %>
        <%= f.select :measure, Product::MEASURES, {}, class: 'form-control' %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :price, 'Preço' %>
    <%= f.number_field :price, min: 1, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit action_text, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/products/cost.html.erb
<div class="card-deck mb-3 text-center">
  <div class="card mb-4 box-shadow">
    <div class="card-header">
      <h4 class="my-0 font-weight-normal">Por mês</h4>
      <%= form_tag cost_products_path, method: "get" do %>
        <%= month_field(:search, :month) %>
        <%= submit_tag 'Filtrar', class: 'btn btn-primary' %>
      <% end %>
    </div>
    <div class="card-body">
      <h1 class="card-title pricing-card-title">R$ <%= @month_costs %> <small class="text-muted">/ mês</small></h1>
      <ul class="list-unstyled mt-3 mb-4">
        <li><%= @month_size %> Produtos foram cadastrados</li>
      </ul>
    </div>
  </div>
  
  <div class="card mb-4 box-shadow">
    <div class="card-header">
      <h4 class="my-0 font-weight-normal">Por semana</h4>
      <%= form_tag cost_products_path, method: "get" do %>
        <%= week_field(:search, :month) %>
        <%= submit_tag 'Filtrar', class: 'btn btn-primary' %>
      <% end %>
    </div>
    <div class="card-body">
      <h1 class="card-title pricing-card-title">R$ <%= @week_costs %> <small class="text-muted">/ semana</small></h1>
      <ul class="list-unstyled mt-3 mb-4">
        <li><%= @week_size %> Produtos foram cadastrados</li>
      </ul>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Editar Produto</h1>

<%= render partial: 'form', locals: {product: @product, action_text: 'Atualizar Produto' } %>

<%= link_to 'Mostrar', @product %> |
<%= link_to 'Voltar', products_path %>

app/views/products/index.html.erb
<%= flash_message %>

<h1>Produtos</h1>

<%= paginate @products %>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th scope="col">Nome</th>
      <th scope="col">Data de compra</th>
      <th scope="col">Data de vencimento</th>
      <th scope="col">Marca</th>
      <th scope="col">Quantidade</th>
      <th scope="col">Medida</th>
      <th scope="col">Preço</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.purchase_date.strftime("%d/%m/%Y") %></td>
        <td><%= product.expiration_date.strftime("%d/%m/%Y") %></td>
        <td><%= product.brand %></td>
        <td><%= product.amount %></td>
        <td><%= product.measure %></td>
        <td>R$ <%= product.price %></td>
        <td><%= link_to 'Mostrar', product %></td>
        <td><%= link_to 'Editar', edit_product_path(product) %></td>
        <td><%= link_to 'Deletar', product, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @products %>

app/views/products/new.html.erb
<%= flash_message %>

<h1>Novo Produto</h1>

<%= render partial: 'form', locals: {product: @product, action_text: 'Novo Produto' } %>

<%= link_to 'Voltar', products_path %>

app/views/products/show.html.erb
<%= flash_message %>

<div class="card">
  <div class="card-body">
    <dl class="row">
      <dt class="col-sm-2">Nome</dt>
      <dd class="col-sm-9"><%= @product.name %></dd>

      <dt class="col-sm-2">Data de compra</dt>
      <dd class="col-sm-9"><%= @product.purchase_date.strftime("%d/%m/%Y") %></dd>

      <dt class="col-sm-2">Data de vencimento</dt>
      <dd class="col-sm-9"><%= @product.expiration_date.strftime("%d/%m/%Y") %></dd>

      <dt class="col-sm-2">Marca</dt>
      <dd class="col-sm-9"><%= @product.brand %></dd>

      <dt class="col-sm-2">Quantidade</dt>
      <dd class="col-sm-9"><%= @product.amount %></dd>

      <dt class="col-sm-2">Medida</dt>
      <dd class="col-sm-9"><%= @product.measure %></dd>

      <dt class="col-sm-2">Preço</dt>
      <dd class="col-sm-9"><%= @product.price %></dd>
    </dl>
  </div>
</div>

<%= link_to 'Editar', edit_product_path(@product) %> |
<%= link_to 'Voltar', products_path %>